ci: change pnpm to npx

diff --git a/devcontainer-images/universal-devcontainer/.devcontainer/Dockerfile b/devcontainer-images/universal-devcontainer/.devcontainer/Dockerfile
--- a/devcontainer-images/universal-devcontainer/.devcontainer/Dockerfile
+++ b/devcontainer-images/universal-devcontainer/.devcontainer/Dockerfile
@@ -1,6 +1,12 @@
+# trunk-ignore-all(trivy/DS002)
+# trunk-ignore-all(trivy/DS026)
+# trunk-ignore-all(checkov/CKV_DOCKER_2)
+# trunk-ignore-all(checkov/CKV_DOCKER_3)
+# trunk-ignore-all(hadolint/SC3020)
+
 FROM buildpack-deps:noble-curl
 
 RUN if id "ubuntu" &>/dev/null; then \
-        userdel -f -r ubuntu || echo "Failed to delete ubuntu user"; \
+      userdel -f -r ubuntu || echo "Failed to delete ubuntu user"; \
     fi;
 
